### ISSUE TITLE
Not sure if you can receive the email, so I create an issue here

### ISSUE THREAD

**Issue by yangfeiran** [WindQAQ/tf-recsys#1]
I am trying to reimplement SVD from the Netflix by using the movies rating.csv, meanwhile I have seen that you have done that on github https://github.com/WindQAQ/tf-recsys/ which is a great work. I used your package, and the RMSE is roughly 0.9 .

However When I am doing that by myself, I can't really get that level: my project is here: https://github.com/yangfeiran/svd

I can hardly push the RMSE below 0.95

I guess you are indeed good at tensorflow and SVD, so I hope it would be fine if I send you a email directly to ask my question :"where is wrong about my project?", cause the only difference I can see is that you are using keras from tensorflow, while I am not.

The reason I would prefer pure tensorflow instead of keras is that: in this way, I can make the code clear enough so everyone can see steps as tensor flows.

And I have created this question on stackoverflow, but no one answered it yet. https://stackoverflow.com/questions/50269129/svd-recommendation-collaborate-filtering-tensorflow

Looking forward for your reply,

Feiran (This is my facebook: https://www.facebook.com/bosilyang, I would be appreciated if you can add me on that)

**Comment by WindQAQ** [comment]
@yangfeiran I have read the code you write, and I think there is no difference between your graph and mine. However, you use `random_uniform` with min=-1, max=1 for the initial values of latent vectors, which is a quite large value for them in my opinion. Have you ever tried to reduce the min/max value? In my project, I use xavier initializer, where the value lies in an relative small range. See [tensorflow xavier initializer](https://www.tensorflow.org/api_docs/python/tf/contrib/layers/xavier_initializer).

Finally, I would like to say I only use the progress bar of keras in this project LOL.

**Comment by yangfeiran** [comment]
@WindQAQ Thank you so much for your answer, it indeed is the problem of the initializer and the regularizer. Now my code works as smooth as yours. Thanks again! I have been studied in National Taipei University of Technology in 2013 for half a year, Taiwan is great, still now!

**Comment by WindQAQ** [comment]
You are welcomed. Feel free to contact me if you have any problem!

**Comment by yangfeiran** [comment]
thank you, it is very kind of you.
